error when path to LLVM contains spaces
fixes #9

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -13,7 +13,7 @@ command -v "${LLVM_CONFIG}" >/dev/null 2>&1 || {
     if [ ! -f "${PREFIX}/bin/llvm-config" ]; then
         mkdir -p "deps"
         FILE="deps/clang-${LLVM_VERSION}.tar.xz"
-        if [ ! -f ${FILE} ]; then
+        if [ ! -f "${FILE}" ]; then
             URL="http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-apple-darwin.tar.xz"
             echo "Downloading ${URL}..."
             curl --retry 3 -# -S -L "${URL}" -o "${FILE}.tmp" && mv "${FILE}.tmp" "${FILE}"
@@ -24,9 +24,15 @@ command -v "${LLVM_CONFIG}" >/dev/null 2>&1 || {
         mkdir -p "${PREFIX}"
         echo -n "Unpacking archive... "
         tar xf "${FILE}" -C "${PREFIX}" --strip-components 1
+        echo "done."
     fi
     LLVM_CONFIG="${PREFIX}/bin/llvm-config"
 }
+
+PREFIX="$("${LLVM_CONFIG}" --prefix)"
+case "${PREFIX}" in
+  *\ *) (>&2 echo "Error: Path to LLVM may not contain spaces: '${PREFIX}'"); exit 1 ;;
+esac
 
 echo "// Do not modify this file. Instead, rerun ./configure" > config.xcconfig
 echo "LLVM_LIBDIR=$(${LLVM_CONFIG} --libdir)" >> config.xcconfig
